### ISSUE TITLE
Use .NET 4.0 instead

### ISSUE THREAD

**Issue by adenovirux** [DaCookie/mindwave-unity#2]
Thanks for the nice project! DaCookie~

This project well in the editor mode, but to build it, .NET 4.x equivalent should be selected for Scripting Runtime Version, otherwise compile errors will be generated and result in a build failure. My system is Unity 2018.1.6f on windows 10.

**Comment by matenestor** [comment]
For those who do not have .NET 4.0, switch to Scripting Runtime Version .NET 3.5 equivalent (although it is deprecated) and API compatibilty level .NET 2.0 (without subset, as DaCookie is suggesting too). 
You might need to rewrite some code, because of older version of .NET, though...
Then your Mindwave shall connect as mine did.
Unity version: 2018.3.8.f1 with Neurosky Mindwave Mobile 2

Also, thanks DaCookie for these scripts, they are really helpful!

**Comment by hubertgdev** [comment]
Thanks for the feedbacks! Sorry for my lateness by the way, but I'm planning to update this package scripts and documentation to latest versions of Unity ;)
